apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: promgrafappns
  name: promgrafapp-deployment
spec:
  selector:
    matchLabels:
      app: promgrafapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      labels:
        app: promgrafapp      
    spec:
      containers:
      - name: promgrafappcont
        image: <your_image>
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 0.25 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: promgrafapp
  namespace: promgrafappns
  name: promgrafapp-service
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 5000
  selector:
    app: promgrafapp
